spring.application.name=java-demo-server

# Basic MCP server attributes
spring.ai.mcp.server.name=java-demo-mcp
spring.ai.mcp.server.version=0.1

# Basic MCP server configuration
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=sync